version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: docker build --rm=false -t jonathanschmalhofer/recursivestereo:latest .
            - run: |
                - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                - docker push jonathanschmalhofer/recursivestereo:latest